version: '3'

services:
  duckdb:
    image: duckdb-image
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --allow-root --notebook-dir=/notebooks
